base:
    version: 1
modules:
    - dtr
config:
    dtr:
        host: 10.10.10.2
        user: admin
        pass: password
# TODO: setup map
tests:
    - name: "create dtr users"
      id: createUsers
      command: "dtr::createUser"
      args:
          username: "test"
          password: "test"
      repeat: 10
