base:
    version: 1
    seed: 89
modules:
    - dtr
    - registry
config:
    dtr:
        host: 10.10.10.2
        user: admin
        pass: password
    docker:
        host: "unix:///var/run/docker.sock"
        version: "v1.23"
    registry:
        host: "https://10.10.10.2/"
tests:
    - name: "create dtr users"
      id: createUsers
      command: "dtr::CreateRandomUser"
      args:
          password: "password"
      repeat: 10
      subtests:
          - name: "create repo for user"
            id: createRepo
            command: "dtr::createRandomRepo"
            args:
                namespace: "createUsers.name"
            repeat: 3
            subtests:
                - name: "create random local image"
                  id: createRandomImage
                  command: "docker::createRandomImage"
                  args:
                      registry: 10.10.10.2
                      namespace: "createUsers.name"
                      reponame: "createRepo.name"
                  subtests:
                      - name: "push random local image"
                        id: pushImage
                        command: "docker::pushRandomImage"
    - name: "push"
      id: push
      command: "registry::PushRandomImage"
      repeat: 5
